//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCnpm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Comments = new HashSet<Comment>();
            this.OrderProes = new HashSet<OrderPro>();
        }

        public int IDCus { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten!")]
        public string NameCus { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten dang nhap!")]
        public string UserCus { get; set; }
        //[RegularExpression(@"[A-Za-z-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        [Required(ErrorMessage = "Vui long nhap email!")]

        public string EmailCus { get; set; }
        [Required(ErrorMessage = "Vui long nhap so dien thoai!")]
        public string PhoneCus { get; set; }
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]

        [Required(ErrorMessage = "Vui long nhap password!")]
        [DataType(DataType.Password)]
        public string PassCus { get; set; }
        [Required(ErrorMessage = "Error ConfirmPassword!")]
        [DataType(DataType.Password)]
        [Compare("PassCus")]
        public string ConfirmPassCus { get; set; }
        public string LoginErrorMessage { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
